version: '3.1'
services:
  app-be:
    image: 'city-list-be:latest'
    ports:
      - "8080:8080"
    container_name: city-list-be
    build:
      dockerfile: DockerFile
      context: ./city-list-be
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cities
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  app-fe:
    container_name: city-list-fe
    image: 'city-list-fe:latest'
    build:
      context: ./city-list-fe
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - app-be

  db:
    image: 'postgres:latest'
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cities
