FROM maven:latest AS maven-build
COPY . /city-list-be
WORKDIR /city-list-be
RUN mvn clean package -DskipTests

FROM openjdk:11
COPY --from=maven-build /city-list-be/target/city-list-be-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
